version: '3.4'

services:
  postgres-test:
    image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:centos8-13.4-4.7.3
    environment:
    - MODE=postgres
    - PG_MODE=primary
    - PG_USER=The12thPlayerUser
    - PG_PASSWORD=The12thPlayerPassword
    - PG_DATABASE=The12thPlayerTest
    - PG_PRIMARY_USER=PrimaryUser
    - PG_PRIMARY_PASSWORD=PrimaryPassword
    - PG_ROOT_PASSWORD=postgres
    - PGHOST=/tmp
    - PG_PRIMARY_PORT=5432
    ports:
    - "5432:5432"

  cockroach-test:
    image: cockroachdb/cockroach:v21.2.3
    ports:
    - "26257:26257"
    - "8080:8080"
    command: start-single-node --insecure

  cockroach-init:
    image: cockroachdb-init:latest
    environment:
    - COCKROACH_HOST=cockroach-test:26257
    - COCKROACH_INSECURE=true
    - DATABASE_NAME=The12thPlayerTest
    - DATABASE_USER=The12thPlayerUser
    depends_on:
    - cockroach-test
  
  rabbit-test:
    image: masstransit/rabbitmq:3.9.7
    ports:
    - "15672:15672"
    - "5672:5672"

  redis-test:
    image: bitnami/redis:6.2.6
    environment:
    - ALLOW_EMPTY_PASSWORD=yes
    ports:
    - "6379:6379"